### ISSUE TITLE
[EPIC] UI

### ISSUE THREAD

**Issue by antfu** [vitest-dev/vitest#346]
- [x] Vue Router + Vite Plugin Pages
- [x] Support `--open` option
- [x] Use Splitpanel to make sidebars resizable: fixed on #389 
- [x] #392
- [ ] Tasks Detail
  - [ ] diff
  - [ ] stacktrace
  - [ ] code frame
  - [x] console.log from user
  - [ ] #1130
- [ ] Module graph inspect (to show transformed code) (WIP @antfu)
- [x] Ensure UI works on Stackblitz

**Comment by DerYeger** [comment]
I'll create a PR for the Splitpanels.

**Comment by userquin** [comment]
I've included all basic tests on `stackblitz` (except internals) here: https://stackblitz.com/edit/vitejs-vite-w46jsw, see `README.md` file.

**Comment by mitchelvanbever** [comment]
Exploring the options to include `user logs` let me know if anyone has already have some thoughts about this.

I'm thinking of adding a `ctx` object to the `task` containing an array of `user logs`.

And do we want this to be a new `tab` (like report of module graph or code) or should we add an accordion/collapsible to the bottom of that same panel which outputs the logs in a more "terminally" kind of fashion?

**Comment by NullVoxPopuli** [comment]
re: https://github.com/vitest-dev/vitest/issues/494
will the stacktrace implementation part of this EPIC have clickable links so I can use browser-tools to set breakpoints and figure out what's going wrong without console.logging?

**Comment by sheremet-va** [comment]
> re: https://github.com/vitest-dev/vitest/issues/494
> 
> will the stacktrace implementation part of this EPIC have clickable links so I can use browser-tools to set breakpoints and figure out what's going wrong without console.logging?

I'm not sure it's possible since the code actually runs inside node and not in the browser
